apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-demo
    component: spring-boot-demo    
  name: spring-boot-demo
  #namespace: synext-demo
spec:
  ports:
    - name: http
      port: 8011
      protocol: TCP
      targetPort: 8011
      nodePort: 30861
  selector:
    app: spring-boot-demo
    component: spring-boot-demo
    tier: backend    
  type: NodePort
